version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./.mvn:/app/.mvn
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
      - mongodb

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=analytics_db
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: